name: "优化建议"
description: "对已有功能的优化或改进建议"
labels: ["B: 优化建议"]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "在提交 issue 之前, 请检查以下两项内容:"
    options:
    - label: "**此建议不涉及模组的增删** 针对需要增删模组的建议, 请前往 [新功能提案](https://github.com/QianFuv/Miracles-Journey/issues/new?template=feature.yml)"
      required: true
    - label: "**不存在重复的建议** 我已在 [Issue-优化建议页面](https://github.com/QianFuv/Miracles-Journey/issues?q=sort%3Aupdated-desc%20is%3Aissue%20label%3A%22B%3A%20%E4%BC%98%E5%8C%96%E5%BB%BA%E8%AE%AE%22) 中搜索并确认, 确认了这一建议未被提交过"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 内容
    description: "详细描述具体需要优化哪些地方, 以及为什么需要这项优化"
  validations:
    required: true
