name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02ddf6cffd338837b45085a7d8a4378ea48503285a828306d53e72572a728764"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
