name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68425d1548f3e849eccb4490e67881ca2b9135a99031a700ea2a061752cf0926"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
