name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4052173ed88f385b155d53f76e563e8d37b8453b2999c75e158b9498c4ec3b23"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
