#两次维修之间的间隔，单位Tick。 20 ticks = 1秒。魔艺原版为200。-1关闭，最小0，默认为20。
#Range: > -1
repairingDelay = 20
#每次维修一个物品（格）时消耗的魔力，单位为Mana/个物品。默认 20。
#Range: > 0
repairingCost = 20
#每次维修提升的耐久值是修复纤维等级+该值，魔艺原版为1。如果为负数可以消耗魔力倒扣耐久。这里默认为0。
#Range: > -2147483648
repairingBonus = 0

