#allBoxes
string_array = ["box", "dzadok", "ulter", "choko", "slime", "csqrb", "roulete", "brass", "kiril", "kiril2", "breaze", "love", "qves", "pelme", "some", "cold", "tomat", "tochn", "portal", "maxi", "card", "nikok", "bearing", "dodobox", "mangtea", "template1", "template2", "template3", "template4", "template5"]

