# Use Cloth Config mod for the descriptions.
---
enable: true
transitionSpeed: 1.0
nimbleMounting: false
mountingEntityBlocklist: []
nimbleElytra: false
elytraRollScreen: true
elytraRollStrength: 20
elytraTickDelay: 10
frontKeyToggleMode: false
expectedThirdPersonDistance: 4.0
