#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jun 18 11:24:38 AEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.7.1 + EuphoriaPatches_1.8.5
