
[Render]
	#Disable CIL(CustomInLevel) render.
	noModRender = false
	#Render TimeStop shock wave effect.
	timestopBall = true

	[Render.CosmicShader]
		#Enable cosmic renderer
		cosmicRenderer = true
		#cosmic shader scale
		cosmicScale = 1.0
		#cosmic texture covering the item
		wrappedTextureLocation = "sakuratinker:textures/shader/star2.png"
		#cosmic render speed multiplier
		#Range: 0.0 ~ 100.0
		cosmicSpeedMultiplier = 1.0

