name: Nightly Build

on:
  push:
    paths:
      - "pack/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pack

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
          cache: false

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Export pack
        id: export
        run: |
          packwiz curseforge export
          echo "PACK_NAME=$(ls *.zip | sed 's/.zip$//')" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create temp directory and unzip
        run: |
          mkdir -p unzipped
          unzip "${{ env.PACK_NAME }}.zip" -d unzipped/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACK_NAME }}-${{ env.SHORT_SHA }}
          path: pack/unzipped/
